FROM webrtc:dev AS builder

WORKDIR /webrtc/frontend

RUN yarn build

FROM nginx:1.19.3-alpine as production


COPY --from=builder /webrtc/frontend/dist /var/www/webrtc
COPY ./nginx/.conf /etc/nginx/conf.d/default.conf